### ISSUE TITLE
Update DEMO link

### ISSUE THREAD

**Issue by Samoji** [daybrush/infinite-viewer#1]
Can you please update the demo page? 
I've tried to do a little demo myself but I didn't reached the expected results.

Thank you in advance

**Comment by daybrush** [comment]
@Samoji 
The demo is still being prepared. However, there is a temporary demo.


See below link:
https://daybrush.com/selecto/storybook/?path=/story/selecto-with-infinite-viewer--select-in-the-infinite-scroll-viewer
