### ISSUE TITLE
How to add events to infinite-viewer-scroll-area element ?

### ISSUE THREAD

**Issue by StringKe** [daybrush/infinite-viewer#14]
The trackpad can be dragged quickly on the mac, and only the scroll bar can be used on the PC. I need to add events in places other than `ViewerContainer`, such as on the `infinite-viewer-scroll-area` element

**Comment by daybrush** [comment]
@StringKe 

infinite-viewer's new version is released.

you can use getScrollArea() method
```js
viewer.getScrollArea().addEventListener("...", () => {});
```
