### ISSUE TITLE
[react-infinite-viewer] The scrollbar is displayed abnormally when content exists on the left side.

### ISSUE THREAD

**Issue by StringKe** [daybrush/infinite-viewer#22]
Example : 

https://codesandbox.io/s/react-infinite-viewer-left-content-bug-7btcsj?file=/src/App.js

![CleanShot 2022-02-17 at 17 52 06@2x](https://user-images.githubusercontent.com/31089228/154450717-dbfc23c4-9890-4fcd-ad5e-02ced8fec0d6.png)

**Comment by daybrush** [comment]
@StringKe 

InfiniteViewer literally scrolls infinitely. The scroll position is almost centered because rangeX left and right are infinite. Scrolling increases left/right.

If you want to limit the amount of scrolling, try setting `rangeX={[0, Infinity]}`
