### ISSUE TITLE
console.log(this.$refs.infiniteViewerRefs.getScrollTop()) is undefined in Vue 2.x.

### ISSUE THREAD

**Issue by xh1996819** [daybrush/infinite-viewer#27]
![image](https://user-images.githubusercontent.com/50142443/167297116-ea0b4e7b-a1e9-4a69-8b14-834f28142179.png)
![image](https://user-images.githubusercontent.com/50142443/167297142-ee98b8e8-4b87-4a34-a533-63d8249162a7.png)

**Comment by daybrush** [comment]
@xh1996819 


vue-infinite-viewer@0.13.1 is released. Try it again.
