### ISSUE TITLE
svelte-infinite-viewer won't compile

### ISSUE THREAD

**Issue by acurrieclark** [daybrush/infinite-viewer#32]
When adding this to a Svelte project, it fails with the error:
```
[ERROR] No matching export in "node_modules/svelte/internal/index.mjs" for import "get_slot_context"

    node_modules/svelte-infinite-viewer/dist/infinite-viewer.esm.js:9:99`
```

You can see the error in this REPL which uses only the example code:

https://svelte.dev/repl/fd7afb013a0540b58154d153580cda02?version=3.50.0

**Comment by daybrush** [comment]
@acurrieclark 

svelte-infinite-viewer 0.15.2 is released. Check it again.

**Comment by acurrieclark** [comment]
Thank you again such a swift response. I will try this now.
