### ISSUE TITLE
How to obtain the relative coordinates of a dragged element (relative to its parent element)

### ISSUE THREAD

**Issue by hhbusui** [daybrush/infinite-viewer#35]
## problem
Hey, author

When dropping the drag item, obtain its relative coordinates。

## operation
![image](https://user-images.githubusercontent.com/43135111/205269970-f0aac464-2620-4efd-93d9-aac4ae1aab5d.png)

## Code structure

![image](https://user-images.githubusercontent.com/43135111/205270560-06cdd8a7-d503-4472-a411-bcff2f71dcfd.png)

Looking forward to your reply，thank you

**Comment by daybrush** [comment]
@hhbusui 

Using `getElementRect` will give you the exact location.

https://github.com/daybrush/moveable/issues/797#issuecomment-1321015856

The hitTest method will give you an idea of how much the hit is, but it's approximate.

```js
moveable.hitTest(element); // 0 ~ 100
```

**Comment by hhbusui** [comment]
Thank you for your reply, which perfectly solved my problem.
