### ISSUE TITLE
Change dragging method

### ISSUE THREAD

**Issue by leidto** [daybrush/infinite-viewer#40]
useMouseDrag prop is great but I should do the same if the middle mouse button pressed. How can I do this?

**Comment by anas-araid** [comment]
Same issue: would it be possible to add dragging via the mouse wheel button (like Figma or Miro)? It would be super helpful!

Thanks a lot @daybrush for your hard work on this project!

**Comment by daybrush** [comment]
@leidto @anas-araid 

If wheel button in dragStart event, stop with `e.stop` function.

```js
viewer.on("dragStart", e => {
     // Abort on wheel button.
     if (e.inputEvent.button === 1) {
        e.stop();
        return;
    }
});
```

**Comment by daybrush** [comment]
@leidto 

I'll probably fix it and release it this week.

**Comment by daybrush** [comment]
@leidto 

infinite-viewer's new version is released. 

Update and set `preventWheelClick` to false.

And use:
```js

viewer.on("dragStart", e => {
     // only  allow wheel
     if (e.inputEvent.button !== 1) {
        e.stop();
        return;
    }
});

```

**Comment by leidto** [comment]
Thank you. It works perfectly!
