### ISSUE TITLE
Zooming is not working for Lit element

### ISSUE THREAD

**Issue by zsoerenm** [daybrush/infinite-viewer#42]
Unfortunately, zooming isn't working for Lit-element. I tried using the already available `lit-infinite-viewer` package as well as my own implementation. In both cases holding `ctrl` while scolling does nothing (the scale value in `transform` doesn't change). Am I doing something wrong?
I tried Firefox and Chromium.

I have created a Codesandbox:
https://codesandbox.io/s/broken-rain-cq8ei5?file=/src/my-component.ts

**Comment by daybrush** [comment]
@zsoerenm 

Try useAutoZoom prop.

```js
html`<lit-infinite-viewer .useAutoZoom=${true}>...</lit-infinite-viewer>`
```

**Comment by zsoerenm** [comment]
Thanks! 
I also needed to add `.wheelScale=${0.001}`. Otherwise the scale went from `1` to `0.001` in a single scroll step.
