### ISSUE TITLE
How to hide the scroll bars if there is no content outside of the current viewing area?

### ISSUE THREAD

**Issue by quinn280** [daybrush/infinite-viewer#44]
Testable Address: https://codesandbox.io/s/zoom-2t797o?file=/src/App.js

I am hoping to toggle displayHorizontalScroll and displayVerticalScroll based on whether there is content in the current viewing area. Is there any way to do this?

For example:

In the photo below, all of the content is inside the current viewing area. In this case I would want the scroll bars to be hidden.       
![content](https://user-images.githubusercontent.com/54292238/226784227-d3f0dc97-f541-4130-badb-f18650c73822.png)

In this photo, there is some content outside of the current viewing area. In this case I would want the scroll bars to be visible.        
![contentoutside](https://user-images.githubusercontent.com/54292238/226784464-af1ce27e-6994-4c33-9a90-3771487c1d34.png)

**Comment by daybrush** [comment]
ok i'll check it out.

I'll try with a configuration similar to Figma.

**Comment by daybrush** [comment]
@quinn280 

infinite-viewers' new version is released. Try it again.
