### ISSUE TITLE
Performance: translate3d, backface-visibility, will-change

### ISSUE THREAD

**Issue by joncursi** [daybrush/infinite-viewer#5]
Can we translate the element in the infinite viewer using `translate3d` rather than the normal `translate`, to improve performance?

See: https://stackoverflow.com/a/12643404

**Comment by joncursi** [comment]
Performance is improved quite a bit by also applying...

* `backface-visibility: hidden` ([more info](https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility))
* `will-change: transform` ([more info](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change))

They each have tradeoffs in terms of render quality vs performance, so maybe we should expose these as props? E.g.:

```jsx
<InfiniteViewer
  backfaceVisibility={true}
  willChange={false}
>
```

**Comment by daybrush** [comment]
@joncursi 

react-infinite-viewer 0.11.0 is released translateZ prop is added.


You can add willChange, backfaceVisibility to css.

**Comment by joncursi** [comment]
Awesome, thanks!
