### ISSUE TITLE
angular v16 dropped view engine support - please upgrade to ivy

### ISSUE THREAD

**Issue by RobinKamps** [daybrush/infinite-viewer#50]
Thank you very much for all your libs and your effort.
angular v16 dropped view engine support - please upgrade to ivy.

**Comment by daybrush** [comment]
@RobinKamps 

Thanks. I will update from angular13 to 16 this week.

**Comment by daybrush** [comment]
@RobinKamps 

ngx-infinite-viewer@0.24.0 is released. Try it again.

**Comment by RobinKamps** [comment]
Thank you very much - it compiles now.

However i was on v0.15 before and i am not able to set the properties like margin etc. - or how to listen to events - since all angular Inputs and Outputs have been removed in previous versions.
`name in this && typeof this[name] !== 'undefined'` from `ngx-infinite-viewer.component.ts` does not work if angular  `fullTemplateTypeCheck` is enabled.

```
PROPERTIES.forEach((name) => {
      if (name in this && typeof this[name] !== 'undefined') {
        (options as any)[name] = this[name];
      }
    });
```

unfortunately, there is no example in the angular section how to set properties or listen to events - can you please provide an example. It would be great to refactor the angular wrapper to support fullTemplateTypeCheck - perhaps it could be done with just one Input for all properties with the existing interface and one Output for all EventEmitters. This will also enable IDE autocompletion for inputs and outputs via language service.

**Comment by daybrush** [comment]
@RobinKamps 

sorry. Input and output are missing.

ngx-infinite-viewer@0.24.1 is released. Try it again.

**Comment by RobinKamps** [comment]
it is working again. Many thanks - you are the best.
