### ISSUE TITLE
Scrollbar regression?

### ISSUE THREAD

**Issue by bytasv** [daybrush/infinite-viewer#51]
Hey there, I noticed that scrollbars started to behave weird, I'm suspecting there might have been a regression introduced at some point?

(Latest version, react) as well as in your live demo: https://daybrush.com/infinite-viewer/

https://github.com/daybrush/infinite-viewer/assets/437214/439a0e7c-d942-4b71-942c-8625ea76f651

If I'm not mistaken this worked fine in the past 🤔

**Comment by daybrush** [comment]
@bytasv 

A new version of infinite-viewer has been updated.

Added `useBounceScrollBar` prop, set it to true.
You get the same scrollbar as the original InfiniteViewer.
