### ISSUE TITLE
ngx-infinite-viewer useBounceScrollBar does not exists

### ISSUE THREAD

**Issue by martinhorvath1** [daybrush/infinite-viewer#57]
I got an error in when I use `useBounceScrollBar `: NG8002: Can't bind to 'useBounceScrollBar' since it isn't a known property of 'ngx-infinite-viewer'

I think the issue is that the consts file the input haven't been specified
https://github.com/daybrush/infinite-viewer/blob/ngx-infinite-viewer%400.26.1/packages/ngx-infinite-viewer/projects/ngx-infinite-viewer/src/lib/consts.ts

version: 0.26.1

**Comment by daybrush** [comment]
@martinhorvath1 

ngx-infinite-viewer's new version is released. Check it again.

**Comment by martinhorvath1** [comment]
Working as expected, thanks!
