### ISSUE TITLE
Scroll Issues on Windows with a Custom Browser Zoom Level

### ISSUE THREAD

**Issue by joncursi** [daybrush/infinite-viewer#6]
When a Windows > Chrome user zooms their browser out (e.g. to 90%) or in (e.g. to 110%), the scroll functionality of this library no longer works.

This issue is reproduce-able on the demo page for this library: https://daybrush.com/infinite-viewer/

## How to Reproduce

1. Open the Chrome browser on a Windows 10 device
2. Navigate to the demo page for this library: https://daybrush.com/infinite-viewer/
3. Zoom your browser out to 90%, or in to 110%
4. Notice that the scroll behavior no longer works. You cannot scroll up or down via mousewheel, or drag either of the scroll bars.

**Comment by lakshay24** [comment]
Hi @joncursi we are getting this as well on MacOS > Chrome.  

Did you manage to find a solution?

**Comment by daybrush** [comment]
@joncursi @lakshay24 

I'll fix it tomorrow.

**Comment by daybrush** [comment]
@joncursi @lakshay24 

infinite-viewer's new version is released. Check it again.

**Comment by joncursi** [comment]
Confirmed working, thank you!

**Comment by geoffbullen** [comment]
Yep!  Many thanks @daybrush
