### ISSUE TITLE
Bug(react-infinite-viewer) : Scroll bar does not disappear immediately

### ISSUE THREAD

**Issue by jiwon79** [daybrush/infinite-viewer#67]
### Problem
We can use the parameter(displayHorizontalScroll, displayVerticalScroll) to decide whether to show a scroll bar. I made visible variable using useState and button that toggle visible variable. However, the scrollbar does not disappear as soon as the button is pressed. After that, you have to scroll a little bit for it to disappear

### Example - Code Sandbox
https://codesandbox.io/p/sandbox/infinite-viewer-r5z5ws?file=%2Fsrc%2FApp.css%3A8%2C16

**Comment by jiwon79** [comment]
I update version `infinite-viewer` `react-infinite-viewer` to 0.29.1 and 0.28.1. However the bug is not solved. Please check it in code sandbox link

**Comment by daybrush** [comment]
I think  it's cached with old version.

if you create a new codesandbox, it look like this.


https://codesandbox.io/s/awesome-payne-6klyyn

**Comment by jiwon79** [comment]
I check that it is currently operating normally. thank you
