### ISSUE TITLE
Can we support VUE 3.0

### ISSUE THREAD

**Issue by tianyuya** [daybrush/infinite-viewer#7]

**Comment by daybrush** [comment]
@tianyuya 

vue-infinite-viewer@0.11.0 is released. Try it again.

**Comment by labbomb** [comment]
![image](https://user-images.githubusercontent.com/15062456/113258467-8e333080-92fe-11eb-9ad9-2499fadfce14.png)
There are some warnings, can it be solved

**Comment by daybrush** [comment]
@tianyuya @labbomb 

`vue3-infinite-viewer` is released.
